### ISSUE TITLE
Click on create chain icon then Inverted Sorter crash :(

### ISSUE THREAD

**Issue by BigSpeck** [blahblahbloopster/mindustry-client#1]
**Platform**: Windows

**Build**: Not sure how to check that, downloaded and compiled .zip from last night

**Issue**: Click on create chain "+" icon then Inverted Sorter and the following crash seems to happen

**Steps to reproduce**: Click on create chain "+" icon then Inverted Sorter and the following crash seems to happen

Crash:

java.lang.NullPointerException
	at mindustry.ui.fragments.PlacementFragment.lambda$null$12(PlacementFragment.java:257)
	at mindustry.world.blocks.ItemSelection.lambda$buildTable$1(ItemSelection.java:30)
	at arc.scene.Element$8.changed(Element.java:1074)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:12)
	at arc.scene.Element.notify(Element.java:172)
	at arc.scene.Element.fire(Element.java:143)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:33)
	at arc.scene.Scene.touchUp(Scene.java:339)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:115)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:104)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:141)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

Thanks for everything, wish you well.

**Comment by blahblahbloopster** [comment]
Fixed!
