### ISSUE TITLE
End pathfinding path button causes a crash when no paths are set.

### ISSUE THREAD

**Issue by BigSpeck** [blahblahbloopster/mindustry-client#2]
**Platform**: *Windows*

**Build**: *Latest posted for download*

**Issue**: *End pathfinding path button causes a crash when no paths are set.*

**Steps to reproduce**: *End pathfinding path button causes a crash when no paths are set.*

Crash log:

java.lang.IllegalStateException: Array is empty.
	at arc.struct.Array.first(Array.java:625)
	at mindustry.ui.fragments.HudFragment.lambda$null$32(HudFragment.java:389)
	at arc.scene.Element.lambda$clicked$2(Element.java:1004)
	at arc.scene.Element$3.clicked(Element.java:1013)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:33)
	at arc.scene.Scene.touchUp(Scene.java:339)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:115)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:104)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:141)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

**Comment by Auserwaulth** [comment]
Can confirm

**Comment by buthed010203** [comment]
This is fixed

**Comment by blahblahbloopster** [comment]
Fixed
